nodes: &NODES
- &A
    name: A
    roles:
    - X-role
- &B
    name: B
    roles:
    - Y-role
    - Z-role
    scaling:
        max: 5
- &C
    name: C
    roles:
    - Q-role
    scaling:
        min: 2
        max: 5
- &D
    name: D
    roles:
    - R-role
infrastructures:
-
    user_id: zfarkas
    expected_output: |
        S A:0 B:0 C:0 D:0
        S A:0 B:0 C:0 D:0
        R A:0 B:0 C:0 D:0
        R A:1 B:0 C:0 D:0
        R A:1 B:1 C:2 D:0
        R A:1 B:1 C:2 D:1
    name: diamond
    nodes: *NODES
    dependencies:
    - [ *D, *C ]
    - [ *D, *B ]
    - [ *B, *A ]
    - [ *C, *A ]
